# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "state-bucket-sandesh-2026"
    encrypt      = true
    key          = "./terraform.tfstate"
    region       = "eu-north-1"
    use_lockfile = true
  }
}
